# Site
#repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Sebastian Ohmsen
title: Freelance Software Engineer and Consultant
email: hello@sebastianohmsen.com
website: sebastianohmsen.com

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  sebastian-ohmsen
xing_username: Sebastian_Ohmsen

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# About Section
about_title: About Me
about_profile_image: images/sebastian-ohmsen.jpg
about_content: > # this will include new lines to allow paragraphs
  Hi, my name is Sebastian and I am a freelance software engineer and consultant. I have 20+ years of experience in creating digital products that focus on a good user experience.


  I love to use <b>requirement analysis</b>, modern <b>architecture patterns</b> and <b>design principles</b> to create a good software architecture that allows me to implement a <b>modular</b> and <b>maintainable</b> solution. 

  <p class="quote">To go beyond is as wrong as to fall short. - <i>Confucius</i></p>

  My goal is to always write well-structured code that is robust and error tolerant. Technics like <b>clean code</b>, and <b>test-driven development</b> are the base of my daily work.


  I have worked with a wide range of program languages and frameworks. The things that I currently use on a daily bases and that I have the most experience with are: <mark>C#</mark>, <mark>Javascript</mark> and <mark>HTML&CSS</mark>, <mark>.Net Razor pages</mark>, <mark>.Net Blazor</mark>, <mark>.Net MVC</mark>, <mark>xUnit</mark>,<mark>NSubstitute</mark>, <mark>FluentAssertions</mark>, <mark>Vite</mark>, <mark>Webpack</mark>, <mark>Mocha</mark>, <mark>Chai</mark>, <mark>Sinon.JS</mark>, and <mark>SASS</mark>.

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (  list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  # - title: Experience # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       title: The Boring Company
  #       link: boringcompany.com
  #       # link_text: boringcompany.com
  #       sub_title: Senior Network System Administrator
  #       caption: November 2017 - Present
  #       quote: >
  #         Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
  #       description: | # this will include new lines to allow paragraphs
  #           Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Hamburg University of Applied Sciences
        caption: 2008 - 2011
        sub_title: MSc Computer Science - Distributed Systems
        description: | 
          During my time as a student in the Master's program, I mainly focused on the different facets of human-machine interaction.
          
          As one of the members of the Ambient Intelligence Institute at the Hamburg University of Applied Sciences, I was involved in the realization of the Living Place Hamburg, one of the first smart home laboratories in Europe. 

          In addition to developing various projects in the lab, I have experienced different perspectives and approaches to technology in various projects with artists, textile technicians and fashion designers.

          One of the highlights of these collaborations was the development of wearable electronic components for interactive clothing by Merrit Ohmsen.

      - layout: left
        title: Hamburg University of Applied Sciences
        caption: 2002 - 2008
        sub_title: BSc Computer Science for Technical Systems
        description: |
          During my degree at Hamburg University of Applied Sciences I learn skills such as developing software in teams or the basics of project management, in addition basics of software architecture, basic knowledge of circuit technology and hardware-related programming. 

          In particular, this included reading and processing a wide variety of sensors. This quickly showed me the challenges of interacting with computers beyond keyboard and mouse interaction. 

  - title: When I'm Not Programming
    layout: text
    content: | 
      When I'm not developing software, I like to spend my time working with wood to build furniture or small utility items. 

      As a father of two children, I also enjoy spending time outdoors with them, whether it's being active in nature, at the beach or discovering new cities and areas. 

      The rest of the time you can find me working on the family bikes or simply relaxing with a good book.

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

# plugins:
#  - jekyll-seo-tag
